version: "3.8"
services:
  mongodb:
    image: mongo:5.0.6
    container_name: senior_project_mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=mydatabase
    ports:
      - 27017:27017
    volumes:
      - ./tmpdata/mongodb_data:/data/db
